// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopTechApi.Data;

#nullable disable

namespace TopTechApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524182913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("OrdemServicoPeca", b =>
                {
                    b.Property<int>("OrdensServicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PecasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdensServicoId", "PecasId");

                    b.HasIndex("PecasId");

                    b.ToTable("OrdemServicoPeca");
                });

            modelBuilder.Entity("OrdemServicoServico", b =>
                {
                    b.Property<int>("OrdensServicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServicosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdensServicoId", "ServicosId");

                    b.HasIndex("ServicosId");

                    b.ToTable("OrdemServicoServico");
                });

            modelBuilder.Entity("TopTechApi.Models.CategoriaPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriasPecas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Placa-Mãe"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Memória RAM"
                        });
                });

            modelBuilder.Entity("TopTechApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TopTechApi.Models.Computador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Computadores");
                });

            modelBuilder.Entity("TopTechApi.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemaRelatado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComputadorId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("OrdensServicos");
                });

            modelBuilder.Entity("TopTechApi.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("TopTechApi.Models.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaPecaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPecaId");

                    b.ToTable("Pecas");
                });

            modelBuilder.Entity("TopTechApi.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("TopTechApi.Models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidade = "Hardware",
                            Nome = "Carlos Silva"
                        },
                        new
                        {
                            Id = 2,
                            Especialidade = "Redes e Software",
                            Nome = "Ana Souza"
                        });
                });

            modelBuilder.Entity("OrdemServicoPeca", b =>
                {
                    b.HasOne("TopTechApi.Models.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdensServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TopTechApi.Models.Peca", null)
                        .WithMany()
                        .HasForeignKey("PecasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrdemServicoServico", b =>
                {
                    b.HasOne("TopTechApi.Models.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdensServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TopTechApi.Models.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopTechApi.Models.Computador", b =>
                {
                    b.HasOne("TopTechApi.Models.Cliente", "Cliente")
                        .WithMany("Computadores")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TopTechApi.Models.OrdemServico", b =>
                {
                    b.HasOne("TopTechApi.Models.Computador", "Computador")
                        .WithMany("OrdensServico")
                        .HasForeignKey("ComputadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TopTechApi.Models.Tecnico", "Tecnico")
                        .WithMany("OrdensServico")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computador");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("TopTechApi.Models.Pagamento", b =>
                {
                    b.HasOne("TopTechApi.Models.OrdemServico", "OrdemServico")
                        .WithMany("Pagamentos")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("TopTechApi.Models.Peca", b =>
                {
                    b.HasOne("TopTechApi.Models.CategoriaPeca", "Categoria")
                        .WithMany("Pecas")
                        .HasForeignKey("CategoriaPecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TopTechApi.Models.CategoriaPeca", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("TopTechApi.Models.Cliente", b =>
                {
                    b.Navigation("Computadores");
                });

            modelBuilder.Entity("TopTechApi.Models.Computador", b =>
                {
                    b.Navigation("OrdensServico");
                });

            modelBuilder.Entity("TopTechApi.Models.OrdemServico", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("TopTechApi.Models.Tecnico", b =>
                {
                    b.Navigation("OrdensServico");
                });
#pragma warning restore 612, 618
        }
    }
}
